### ISSUE TITLE
d3 and topojson dependency

### ISSUE THREAD

**Issue by moklick** [chriswhong/leaflet-globeminimap#1]
I didn't tested it yet, but I am sure it will not work with AMD or CommonJS, because you are not requiring d3 and topojson.

**Comment by chriswhong** [comment]
Thank you for raising this issue.  What's the best way to get it compliant with CommonJS and AMD?

**Comment by moklick** [comment]
I will open a pull request. Another problem could be the path of the json file. In the readme you are saying, that you are looking under "data/word.json" but in the minified version you are using this path "minimap/src/world.json". Maybe it would make sense to add an option (for example "dataSrc"), where to look for this file.

**Comment by chriswhong** [comment]
I just opened another issue on this... does it even need to be an external
file?  Putting it in the main js file could work too but is ugly
